### ISSUE TITLE
avoid using import go.capnp

### ISSUE THREAD

**Issue by vtolstov** [jmckaskill/go-capnproto#14]
Is that possible to automatic prepend contents of go.capnp when generating go files?
As i see i need to have this file in all my projects and update when new version comes.

**Comment by jmckaskill** [comment]
I'm not sure I understand your request, but I think the answer is no. The annotations from go.capnp ($Go.package and $Go.import) are needed in order to generate .go files. These provide extra information that is required in order to generate valid go code that is not otherwise included in the capnp files. Providing this information via the command line wouldn't work as this information is also required when including other capnp files which is potentially in a different library.

However you do not need to include the go.capnp directly from go-capnproto. The annotation IDs will remain stable, so there are actually three ways to define the import and package:

1) Include go.capnp from go-capnproto and define $Go.package and $Go.import
2) Copy go.capnp into your own project, include and define $MyGo.package and $MyGo.import
3) Copy the two annotations and define in your individual file. For example:

annotation package @0xbea97f1023792be0 (file) :Text;
annotation import @0xe130b601260e44b5 (file) :Text;

# needed to know what package should be used for generated code

$package("main");

# Needed to know how to import types in the capnp file and whether two

# capnp files are in the same package

$import("github.com/jmckaskill/go-capnproto/example");

@0x832bcc6686a26d56;

struct Zdate {
  year  @0   :Int16;
  month @1   :UInt8;
  day   @2   :UInt8;
}

You do not need to worry about updating the go.capnp file in case 2 above. Any changes to go.capnp will be strictly optional additions. Any additional required annotations or modifications to the package and import annotations would break the API as everyone would then have to update their capnp files.

**Comment by vtolstov** [comment]
Thanks! I'm already copy/paste id from go.capnp file, as you say id is stable thing i think that this best for me. Thanks!
